services:
  frontend:
    build:
      context: ../frontend
    restart: unless-stopped
    container_name: vue
    ports:
      - "80:80"

  backend:
    build:
      context: ../backend
    restart: unless-stopped
    container_name: express
    ports:
      - "8080:80"

  db:
    image: redis
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - data:/data

volumes:
  data:
