- hosts: all
  become: true
  vars:
    app_repo: "https://github.com/J-C-V/dhbw-cc-translate.git"
    app_directory: "/app"
    backend_directory: "/app/backend"
    frontend_directory: "/app/frontend"
    backend_url: "<<<BACKEND-URL>>>"
    redis_host: "<<<REDIS-HOST>>>"
    redis_port: "6379"
    credentials_file_path_on_host: "gcp_credentials.json"
    credentials_directory: "/root/.config/gcloud"
    credentials_file_path_on_vm: "/root/.config/gcloud/gcp_credentials.json"

  tasks:
    - name: Install Git and Docker
      apt:
        name:
          - git
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Create credentials directory
      ansible.builtin.file:
        path: "{{ credentials_directory }}"
        state: directory

    - name: Copy credentials to VM
      ansible.builtin.copy:
        src: "{{ credentials_file_path_on_host }}"
        dest: "{{ credentials_file_path_on_vm }}"
        mode: '0400'

    - name: Create app directory
      ansible.builtin.file:
        path: "{{ app_directory }}"
        state: directory

    - name: Clone the repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_directory }}"
        clone: yes
        update: yes

    - name: Build backend image
      docker_image:
        build:
          path: "{{ backend_directory }}"
        name: translator-backend
        source: build

    - name: Build frontend image
      docker_image:
        build:
          path: "{{ frontend_directory }}"
          args:
            VITE_BACKEND_URL: "{{ backend_url }}"
        name: translator-frontend
        source: build

    - name: Run backend container
      docker_container:
        name: translator-backend
        image: translator-backend
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:80"
        env:
          REDIS_HOST: "{{ redis_host }}"
          REDIS_PORT: "{{ redis_port }}"
          GOOGLE_APPLICATION_CREDENTIALS: "{{ credentials_file_path_on_vm }}"
        volumes:
          - "{{ credentials_file_path_on_vm }}:{{ credentials_file_path_on_vm }}"

    - name: Run frontend container
      docker_container:
        name: translator-frontend
        image: translator-frontend
        state: started
        restart_policy: unless-stopped
        ports:
          - "80:80"
